[package]
name = "news_fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
config = { path = "../config" }
infra= { path = "../infra" }
logger = { path = "../logger" }

tracing = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }