[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
# 同じworkspace内の別クレート
kernel = { path = "../kernel" }
shared = { path = "../shared" }
config= { path = "../config" }
logger= { path = "../logger" }
http_client = { path = "../http_client" }

tracing-subscriber = { workspace = true }
tokio = { workspace = true }