[package]
name = "notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
config = { path = "../config" }
infra= { path = "../infra" }
logger = { path = "../logger" }
http_client = { path = "../http_client" }

tracing = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
